name: GithubAction2

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Intialize Repo
      uses: actions/checkout@v5

      -name: Install Node
      uses: actions/setup-node@v3
      with: 
        node-version: 16
      
      -name: install dependencies
      run: npm install

      -name: run tests
      run: npm test
